name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: Check TypeScript types
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check types
        run: yarn typecheck --pretty false

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check formatting
        run: yarn format --check
