name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: Check TypeScript types
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check types
        run: yarn tsc --noEmit --pretty false
