name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: Check TypeScript types
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check types
        run: yarn typecheck --pretty false

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check formatting
        run: yarn format --check
